apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    purpose: demonstrate-command
spec:
  containers:
  - name: command-demo-container
    image: busybox
  - command:
        - "sleep"
        - "100"
