apiVersion: v1
kind: Service
metadata:
  name: myapp
spec:
  selector:
    app: myapp
  type: ClusterIP
  ports:
  - name: myapp-srv
    protocol: TCP
    port: 80
    targetPort: myapp-nginx