apiVersion: v1
kind: Service
metadata:
  name: myapp
  namespace: default
spec:
  selector:
    app: myapp
  type: NodePort
  ports:
  - name: myapp-srv
    protocol: TCP
    port: 80
    targetPort: myapp-nginx
    nodePort: 30007